apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: kubegres-system
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  S3_BUCKET: "url-s3"
  ACCESS_KEY: key
  SECRET_KEY:  key
  BUCKET: s3://bucket-name
